### ISSUE TITLE
ruby-devel not available

### ISSUE THREAD

**Issue by jbd214** [linux-on-ibm-z/docs#1]
I am trying to follow the steps on https://github.com/linux-on-ibm-z/docs/wiki/Building-Chef-Client-12.4.0
for RHEL 7.1

Step 1 includes instaling ruby-devel, which is not available. How can I work around that. 

Thank you

**Comment by rposts** [comment]
Hello,

You will require access to supplemental/optional repository - this package should be available from there: https://github.com/linux-on-ibm-z/docs/wiki/Adding-RHEL-Optional-and-Supplementary-Repositories

Thanks.

**Comment by jbd214** [comment]
Thank you.
