### ISSUE TITLE
Grafana build seems to be OK on RHEL and SLES, but browser displays a black screen at logon

### ISSUE THREAD

**Issue by djc2k** [linux-on-ibm-z/docs#13]
Didn't notice any errors during the build, but it displays a black screen for the logon url; e.g.,
http://148.100.5.109:3000/login
The Grafana server console output shows the incoming request, but why the browser is displaying a black screen?

![g1](https://user-images.githubusercontent.com/3653878/32084729-b58cf6a8-ba7f-11e7-8190-1c83526eab2b.JPG)

**Comment by cwsolee** [comment]
Likely environment related matter, say ports needed is open/available, firewall etc...
