### ISSUE TITLE
Knife fails with error

### ISSUE THREAD

**Issue by jbd214** [linux-on-ibm-z/docs#2]
I eventually got chef installed. However this is what I get when I run knife:
[root@zlxcchf1 pkg]# knife
/usr/local/share/gems/gems/chef-12.4.0/Gemfile not found

**Comment by rposts** [comment]
It seems like your gem environment may not be set correctly.  As per step 6:

"export GEM_HOME=/home/<USER>/.gem/ruby
export PATH=/home/<USER>/.gem/ruby/bin:$PATH
Where <USER> is the standard user you are installing under.
Note: Run gem env to verify the state of the environment, if later on you have issues installing / running ruby gems please ensure the environment is set correctly."

Let me know if that works.

Thanks.

**Comment by jbd214** [comment]
Hi 
Thanks for your help. I did get it to work. Not sure what changed. 

But pretty sure, I had to perform the steps as root rather than a regular user. 

I don't know much about ruby, gems, etc. 
but I thought it was strange that the install location is the source location. 

[root@zlxcchf1 chef-config]# bundle show chef-config
/root/chef/chef/chef-config
[root@zlxcchf1 chef-config]#
