### ISSUE TITLE
auditbeat for s390x

### ISSUE THREAD

**Issue by jesslh** [linux-on-ibm-z/docs#21]
Hi, I am building an auditbeat for s390x, following the next guide: https://github.com/linux-on-ibm-z/docs/wiki/Building-Beats

The version that I download of beats was first 6.4, then 6.2 in order to follow the guide.

In both cases, the beat compile but when I run the auditbeat the following error is shown:

ERROR instance/beat.go:758 Existing: 1 error: 1 error: failed to create audit client; failed to get audit status: failed to get audit status ack: no reply received.

auditd service is stopped
Operating System: Linux s390x (3.10 kernel version)

**Comment by cwsolee** [comment]
Which distro are u using?

**Comment by jesslh** [comment]
Red Hat 7.4

**Comment by cwsolee** [comment]
Thanks, looks broken now, it was ok when we publish the instruction, we'll take a look.

**Comment by jesslh** [comment]
Thank you. I'll wait for your answer.

**Comment by cwsolee** [comment]
Build instruction updated, a new fix is needed, let me know if u still c issues.

**Comment by cwsolee** [comment]
I assume everything is ok now, closing.
