### ISSUE TITLE
Building Hyperledger in 2019

### ISSUE THREAD

**Issue by and1234567** [linux-on-ibm-z/docs#25]
Is Building Hyperledger a serious documentation? 
There are so many bugs I don't know where to start...
Is there by chance a hidden updated version of this documentation?

**Comment by cwsolee** [comment]
The timestamp will give u a hint on how outdated it is, because it's not needed anymore, we usually don't delete document here but latest reference is always updated, check here http://ibm.biz/LoZOpenSourceVerifiedList.
