### ISSUE TITLE
glusterfs build on s390x SLES12 SP4 

### ISSUE THREAD

**Issue by AnitaNayak** [linux-on-ibm-z/docs#28]
Glusterfs build steps available on sles12 sp3. But when trying the same step on SLES12 SP4, getting few packages not found, and for which Image is not getting built. SLES12 SP3 is soon getting decrecated in ICP 3.2. Now we are blocked to build glusterfs on SLES12 SP4.

**Comment by cwsolee** [comment]
Our next currency round will try to add SLES12 SP4.

**Comment by AnitaNayak** [comment]
closing the issue.
