### ISSUE TITLE
Building GCC 4.8: missing step/dependancy/something?

### ISSUE THREAD

**Issue by OwenBrotherwood** [linux-on-ibm-z/docs#3]
[Building GCC 4.8](https://github.com/linux-on-ibm-z/docs/wiki/Building-GCC-4.8) may be missing step/dependancy/something.

The system is an "out of the box" RHEL6.7_IMAGE on [IBM LinuxONE Community Cloud](https://developer.ibm.com/linuxone). 
Only yum's applied to the "out of the box" RHEL6.7_IMAGE, apart from the guide, are xauth, xterm and firefox: a bare bones installation of sorts.

If someone can save me time, point out the obvious 

Br Owen

---

Reason for using guide is [BM SDK for Node.js, Version 4: Current news
](http://www-01.ibm.com/support/docview.wss?uid=swg21968931) 
RHEL7.X is not available on IBM LinuxONE Community Cloud.

---

```
In file included from /usr/include/features.h:385:0,
                 from /usr/include/stdio.h:28,
                 from ../../../../gcc-4.8.5/libgcc/../gcc/tsystem.h:87,
                 from ../../../../gcc-4.8.5/libgcc/libgcc2.c:27:
/usr/include/gnu/stubs.h:7:27: fatal error: gnu/stubs-32.h: No such file or directory
 # include <gnu/stubs-32.h>
                           ^
compilation terminated.
make[4]: *** [_muldi3.o] Error 1
make[4]: Leaving directory `/home/linux1/g/gccbuild/s390x-ibm-linux-gnu/32/libgcc'
make[3]: *** [multi-do] Error 1
make[3]: Leaving directory `/home/linux1/g/gccbuild/s390x-ibm-linux-gnu/libgcc'
make[2]: *** [all-multi] Error 2
make[2]: Leaving directory `/home/linux1/g/gccbuild/s390x-ibm-linux-gnu/libgcc'
make[1]: *** [all-target-libgcc] Error 2
make[1]: Leaving directory `/home/linux1/g/gccbuild'
make: *** [all] Error 2

```

Edit
Investigating missing glibc-devel.s390 as possible dependancy

**Comment by OwenBrotherwood** [comment]
(Building GCC 4.8)[https://github.com/linux-on-ibm-z/docs/wiki/Building-GCC-4.8]

On step 1:
- add yum package glibc-devel.s390 
  - can help others with time/energy to obtain a first time build sucess

**Comment by joransiu** [comment]
@OwenBrotherwood Thanks for pointing out the missing package dependency.

/cc @bryanpkc

**Comment by bryanpkc** [comment]
@OwenBrotherwood Thanks for the feedback. I have updated the instructions in the wiki page.

**Comment by OwenBrotherwood** [comment]
:+1:
