### ISSUE TITLE
Error building Elasticsearch

### ISSUE THREAD

**Issue by madleit** [linux-on-ibm-z/docs#34]
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file '/root/elasticsearch/benchmarks/build.gradle' line: 20

* What went wrong:
A problem occurred evaluating project ':benchmarks'.
> Failed to apply plugin [id 'elasticsearch.build']
   > Cannot set maxParallelForks to a value less than 1.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':benchmarks'.
> Failed to notify project evaluation listener.
   > Must specify license and notice file for project :benchmarks
   > Must specify license and notice file for project :benchmarks
   > Must specify license and notice file for project :benchmarks

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 44s

**Comment by aborkar-ibm** [comment]
This looks to be an intermittent issue. Could you also please share the distro (Ubuntu 16.04/18.04 or any other) on which you get this error? I just followed the instructions on Ubuntu 18.04 and it built successfully for me.
