### ISSUE TITLE
build_kibana.sh - ENOSPC on yarn bootstrap

### ISSUE THREAD

**Issue by pholm07** [linux-on-ibm-z/docs#35]
Using build_kibana.sh building Kibana 741 with 13GB of free disk space ends with ENOSPC end of disk space. Please see the log below.
Eventually I got it working with 17GB of free disk space, but really there must be something wrong as the Kibana install is only around 400MB.
As I'm upgrading from ELK 720 it was also annoying that I needed to delete the directories (kibana, logstash, elasticsearch) in /usr/share and also the symbolic links in /usr/bin /node, npm, npx) otherwise the script fails.
Now running ELK 741 on RHEL 7.7 on Linux on z :-)
/Peter
error An unexpected error occurred: "ENOSPC: no space left on device, copyfile '/home/elk1/.cache/yarn/v6/npm-rxjs-6.4.0-f3bb0fe7bda7fb69deac0c16f17b50b0b8790504-integrity/node_modules/rxjs/_esm2015/internal/operators/pluck.js.map' -> '/opt/install-elk/kibana-741/kibana/node_modules/eslint/node_modules/rxjs/_esm2015/internal/operators/pluck.js.map'".
info If you think this is a bug, please open a bug report with the information provided in "/opt/install-elk/kibana-741/kibana/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/installfor documentation about this command.
 
[bootstrap] failed:
 
Error: Command failed: yarn install --non-interactive
    at makeError (/opt/install-elk/kibana-741/kibana/packages/kbn-pm/dist/index.js:19129:9)
    at Promise.all.then.arr (/opt/install-elk/kibana-741/kibana/packages/kbn-pm/dist/index.js:19233:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/runfor documentation about this command.
[elk1@rl210619 kibana-741]$

**Comment by lcada** [comment]
it actually inflates quite a bit as it builds (dragging all the dependencies etc in)

**Comment by pholm07** [comment]
Managed with larger disk space
