### ISSUE TITLE
wolfssl / mariadb

### ISSUE THREAD

**Issue by grooverdan** [linux-on-ibm-z/docs#39]
Hi,

Noticed MariaDB listed in the [Jan 2020 report](https://community.ibm.com/community/user/ibmz-and-linuxone/blogs/elizabeth-k-joseph1/2020/02/14/linuxone-open-source-software-report-january-2020?CommunityKey=87042487-940e-49cc-ae6d-5a5b76c5ea7e&Tab=)

They are having troubles [MDEV-21705](https://jira.mariadb.org/browse/MDEV-21705) with the bundled wolfSSL per https://github.com/wolfSSL/wolfssl/issues/2828.

Hoping someone can help them out.

**Comment by cwsolee** [comment]
Thanks for the comment, we've been using openSSL so far but will take a look at wolfSSL.

**Comment by cwsolee** [comment]
We took a quick look, the issue seems to be quite involved and a proper fix/port will be needed. WolfSSL community seems to be working on it.

**Comment by grooverdan** [comment]
FYI Wolfssl community has fixed this and based on https://buildbot.mariadb.org/#/builders/309/builds/534/steps/6/logs/stdio was built with wolfssl-4.8.0 and runs through a set of s390x ssl based tests without failing.

In the mean time Debian/Ubuntu has relaxed their stance of openssl linking and that is used by default anyway.
