### ISSUE TITLE
Support for Redhat 8.x for Node Exporter

### ISSUE THREAD

**Issue by wlargou** [linux-on-ibm-z/docs#47]
Hi,

Any plans for supporting builds on Redhat 8.x ?

Thank you

**Comment by aborkar-ibm** [comment]
Hello,

You can download and use the binaries. Check for link here -> https://github.com/linux-on-ibm-z/docs/wiki/Building-Prometheus

**Comment by wlargou** [comment]
Thank you, indeed found plenty there.
