### ISSUE TITLE
elasticsearch 7.16.3 does not start on Debian 10 Buster

### ISSUE THREAD

**Issue by wbx-github** [linux-on-ibm-z/docs#51]
Hi,

after successfully creating a deb I try to start elasticsearch the first time.
I get following Exception:
 Exception in thread "main" java.lang.NoSuchFieldError: LUCENE_8_8_2 .

Any idea what I made wrong?
best regards
 Waldemar

**Comment by aborkar-ibm** [comment]
Hi,

The instructions mentioned in https://github.com/linux-on-ibm-z/docs/wiki/Building-Elasticsearch should work fine. Could you try by creating tar distribution, as mentioned in Step 5.

Regards

**Comment by wbx-github** [comment]
Hi,
it was a misconfiguration on our build server a symlink from /usr/share/elasticsearch to /build/elastic to an older elastic build directory. Sorry for the noise.
best regards
 Waldemar
