### ISSUE TITLE
Build Script for Elasticsearch 8.7.0

### ISSUE THREAD

**Issue by bsherman101** [linux-on-ibm-z/docs#55]
Hello,

Great work on all of these build scripts, they have been very helpful.

It would be great if you could update the Elasticsearch and Kibana builds with their newest 8.7.0 version.

Thank you.

**Comment by cwsolee** [comment]
Thanks, our latest validated is 8.6 and we do plan to do another round of currency soon but could be 8.7 or beyond.

**Comment by bsherman101** [comment]
OK understand.  Another quick question.

When I  build and then run 8.6.0 it says in the logs that the version running is "8.6.0-SNAPSHOT" and is a "pre-release version and not recommended for production use".

I see in your build script your checking out v8.6.0

git checkout v$PACKAGE_VERSION

I thought v8.6.0 is a production tag in their code.  Do you know where this is coming from?

**Comment by aborkar-ibm** [comment]
Hello,

As per community, SNAPSHOT is added to locally built distributions. [Reference Link](https://discuss.elastic.co/t/using-embedded-version-of-elastic-gives-this-warning/84299/9?u=namb)
