### ISSUE TITLE
package python-pytz not found

### ISSUE THREAD

**Issue by djc2k** [linux-on-ibm-z/docs#7]
System: SLES 12 SP2

Installing the dependencies for PhantomJS:
sudo zypper install -y gcc gcc-c++ make flex bison gperf ruby openssl-devel freetype-devel fontconfig-devel libicu-devel sqlite-devel libpng-devel libjpeg-devel python python-devel python-setuptools git xorg-x11-devel xorg-x11-essentials xorg-x11-fonts xorg-x11 xorg-x11-util-devel libXfont-devel libXfont1 python-pytz

Got an error: Package 'python-pytz' not found

**Comment by aborkar-ibm** [comment]
Package python-pytz is available on SUSE. Check this link. https://www.suse.com/support/update/announcement/2017/suse-ru-20170981-1/ 

Do you have the module SLE-Module-Public-Cloud enabled?

**Comment by djc2k** [comment]
I'm doing this on the LinuxONE Community Cloud.  Are there any specific instructions for this environment?

**Comment by aborkar-ibm** [comment]
Can you please check which repos are added on your VM.
Try adding the Package_repositories#OSS (https://en.opensuse.org/Package_repositories#OSS). You can use zypper ar <url> <alias> command to add the repo.

**Comment by cwsolee** [comment]
We don't manage LinuxONE community cloud VM do we might be guessing here, I think their website has a way to ask question or I think any user can send email to this ID linux1@us.ibm.com. Just hope my information is still current.
