### ISSUE TITLE
Building Grafana v4.3.2 - does it support RHEL 7.2?

### ISSUE THREAD

**Issue by djc2k** [linux-on-ibm-z/docs#8]

**Comment by cwsolee** [comment]
We didn't verify on RHEL 7.2 but I'm quite sure 7.3 instruction work the same on 7.2. Let me know if u encounter problem with 7.2.

**Comment by djc2k** [comment]
On RHEL 7.2, I got to the last step (make build-js) before it failed.  

Got an error while loading "sass.js" tasks...
>> Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (s390x) with Node.js 6.x

see attached screen shot:
![grafana build rhel7 2 error](https://user-images.githubusercontent.com/3653878/28478754-8ed62f4c-6e0e-11e7-9a07-ab27ad241e8e.JPG)

**Comment by cwsolee** [comment]
Little unusual, we'll take a look, will get back to u.

**Comment by djc2k** [comment]
Thanks.  By the way, I'm doing this on the LinuxONE Community Cloud.

**Comment by cwsolee** [comment]
Ok thanks, good to know.

**Comment by cwsolee** [comment]
We tried our steps on RHEL 7.2, the same instruction works for us but we don't have LINUXONE Community Cloud server.
